apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kyverno
resources:
  - upstream/install.yaml
  - policies/disallow-privileged.yaml
  - policies/require-labels.yaml
  - policies/add-env-label.yaml
patches:
  - path: patches/webhook-aks.yaml
    target:
      kind: ValidatingWebhookConfiguration
  - path: patches/webhook-aks.yaml
    target:
      kind: MutatingWebhookConfiguration
  - path: patches/system-pool.yaml
    target:
      kind: Deployment
      namespace: kyverno