apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-karpenter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: laurel-poc
  source:
    repoURL: https://github.com/gasper-az/aks-laurel-poc.git
    targetRevision: HEAD
    path: platform/karpenter
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true