albController:
  namespace: azure-alb-system
  podIdentity:
    clientID: "c4aef77d-fb5a-4b8b-9eb5-a728fa5a7d34"
  controller:
    replicaCount: 2
    nodeSelector:
      pool: system
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
  installGatewayApiCRDs: true