apiVersion: apps/v1
kind: Deployment
metadata:
  name: unused
  namespace: kyverno
spec:
  template:
    spec:
      nodeSelector:
        pool: system
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists